# -*- coding: utf-8 -*-
"""
Created on Sun Mar  1 13:30:58 2020

@author: kaica
"""
def Person_Brackets_list():
     test_list= [[['Virginia', 0],#Person 1
     ['Tennessee', 0],
     ['Purdue', 0],
     ['Wisconsin', 0],
     ['Villanova', 0],
     ['Kansas State', 0],
     ['Cincinnati', 0],
     ['Mississippi', 0],
     ['Virginia', 1],
     ['Tennessee', 1],
     ['Villanova', 1],
     ['Kansas State', 1],
     ['Virginia', 2],
     ['Tennessee', 2],
     ['Virginia', 3],
     ['North Carolina', 0],
     ['Kentucky', 0],
     ['Auburn', 0],
     ['Houston', 0],
     ['Northeastern', 0],
     ['Iowa State', 0],
     ['Wofford', 0],
     ['Washington', 0],
     ['North Carolina', 1],
     ['Kentucky', 1],
     ['Auburn', 1],
     ['Iowa State', 1],
     ['Auburn', 2],
     ['Kentucky', 2],
     ['Kentucky', 3],
     ['Duke', 0],
     ['Michigan State', 0],
     ['Virginia Tech', 0],
     ['Louisiana State', 0],
     ['Minnesota', 0],
     ['Belmont', 0],
     ['Mississippi State', 0],
     ['Virginia Commonwealth', 0],
     ['Duke', 1],
     ['Michigan State', 1],
     ['Virginia Tech', 1],
     ['Louisiana State', 1],
     ['Virginia Tech', 2],
     ['Michigan State', 2],
     ['Michigan State', 3],
     ['Temple', 3],
     ['Gonzaga', 0],
     ['Montana', 0],
     ['Texas Tech', 0],
     ['Florida State', 0],
     ['Nevada', 0],
     ['Buffalo', 0],
     ['Marquette', 0],
     ['Syracuse', 0],
     ['Gonzaga', 1],
     ['Texas Tech', 1],
     ['Florida State', 1],
     ['Nevada', 1],
     ['Florida State', 2],
     ['Texas Tech', 2],
     ['Texas Tech', 3],
     ["St. John's (NY)", 3],
     ['Virginia', 4],
     ['Michigan State', 4],
     ['Michigan State', 5]]
     ,[['Virginia', 0], #Second Person
     ['Tennessee', 0],
     ['Purdue', 0],
     ['Villanova', 0],
     ['Wisconsin', 0],
     ['UC-Irvine', 0],
     ['Cincinnati', 0],
     ['Oklahoma', 0],
     ['Virginia', 1],
     ['Cincinnati', 1],
     ['Purdue', 1],
     ['Wisconsin', 1],
     ['Virginia', 2],
     ['Purdue', 2],
     ['Virginia', 3],
     ['North Carolina', 0],
     ['Kentucky', 0],
     ['Auburn', 0],
     ['Kansas', 0],
     ['Houston', 0],
     ['Ohio State', 0],
     ['Wofford', 0],
     ['Utah State', 0],
     ['North Carolina', 1],
     ['Kentucky', 1],
     ['Auburn', 1],
     ['Houston', 1],
     ['North Carolina', 2],
     ['Houston', 2],
     ['North Carolina', 3],
     ['North Dakota State', 0],
     ['Michigan State', 0],
     ['Virginia Tech', 0],
     ['Louisiana State', 0],
     ['Maryland', 0],
     ['Mississippi State', 0],
     ['Minnesota', 0],
     ['Virginia Commonwealth', 0],
     ['Michigan State', 1],
     ['Virginia Tech', 1],
     ['Louisiana State', 1],
     ['Virginia Commonwealth', 1],
     ['Louisiana State', 2],
     ['Virginia Tech', 2],
     ['Virginia Tech', 3],
     ['Gonzaga', 0],
     ['Michigan', 0],
     ['Texas Tech', 0],
     ['Florida State', 0],
     ['Buffalo', 0],
     ['Florida', 0],
     ['Murray State', 0],
     ['Baylor', 0],
     ['Gonzaga', 1],
     ['Michigan', 1],
     ['Texas Tech', 1],
     ['Florida State', 1],
     ['Gonzaga', 2],
     ['Michigan', 2],
     ['Gonzaga', 3],
     ['Virginia', 4],
     ['Gonzaga', 4],
     ['Gonzaga', 5]],
    [['Virginia', 0],
     ['Purdue', 0],
     ['Oregon', 0],
     ['Tennessee', 0],
     ['Oklahoma', 0],
     ['UC-Irvine', 0],
     ['Villanova', 0],
     ['Iowa', 0],
     ['Virginia', 1],
     ['Purdue', 1],
     ['Oregon', 1],
     ['Tennessee', 1],
     ['Virginia', 2],
     ['Purdue', 2],
     ['Virginia', 3],
     ['Auburn', 0],
     ['Kentucky', 0],
     ['North Carolina', 0],
     ['Houston', 0],
     ['Washington', 0],
     ['Kansas', 0],
     ['Ohio State', 0],
     ['Wofford', 0],
     ['Auburn', 1],
     ['Kentucky', 1],
     ['North Carolina', 1],
     ['Houston', 1],
     ['Auburn', 2],
     ['Kentucky', 2],
     ['Auburn', 3],
     ['Michigan State', 0],
     ['Duke', 0],
     ['Virginia Tech', 0],
     ['Louisiana State', 0],
     ['Central Florida', 0],
     ['Liberty', 0],
     ['Maryland', 0],
     ['Minnesota', 0],
     ['Michigan State', 1],
     ['Duke', 1],
     ['Virginia Tech', 1],
     ['Louisiana State', 1],
     ['Michigan State', 2],
     ['Duke', 2],
     ['Michigan State', 3],
     ['Texas Tech', 0],
     ['Gonzaga', 0],
     ['Florida State', 0],
     ['Michigan', 0],
     ['Baylor', 0],
     ['Murray State', 0],
     ['Buffalo', 0],
     ['Florida', 0],
     ['Texas Tech', 1],
     ['Gonzaga', 1],
     ['Florida State', 1],
     ['Michigan', 1],
     ['Texas Tech', 2],
     ['Gonzaga', 2],
     ['Texas Tech', 3],
     ['Virginia', 4],
     ['Texas Tech', 4],
     ['Virginia', 5]],
     
     [['Virginia', 0],
     ['Tennessee', 0],
     ['Purdue', 0],
     ['Wisconsin', 0],
     ["Saint Mary's (CA)", 0],
     ['Kansas State', 0],
     ['Cincinnati', 0],
     ['Mississippi', 0],
     ['Virginia', 1],
     ['Tennessee', 1],
     ['Purdue', 1],
     ['Kansas State', 1],
     ['Virginia', 2],
     ['Purdue', 2],
     ['Purdue', 3],
     ['North Carolina', 0],
     ['Kentucky', 0],
     ['Auburn', 0],
     ['Houston', 0],
     ['Kansas', 0],
     ['Ohio State', 0],
     ['Wofford', 0],
     ['Utah State', 0],
     ['North Carolina', 1],
     ['Kentucky', 1],
     ['Auburn', 1],
     ['Houston', 1],
     ['Auburn', 2],
     ['Kentucky', 2],
     ['Auburn', 3],
     ['North Dakota State', 0],
     ['Michigan State', 0],
     ['Virginia Tech', 0],
     ['Louisiana State', 0],
     ['Louisville', 0],
     ['Maryland', 0],
     ['Mississippi State', 0],
     ['Virginia Commonwealth', 0],
     ['Michigan State', 1],
     ['Virginia Tech', 1],
     ['Louisiana State', 1],
     ['Virginia Commonwealth', 1],
     ['Louisiana State', 2],
     ['Virginia Tech', 2],
     ['Virginia Tech', 3],
     ['North Carolina Central', 3],
     ['Gonzaga', 0],
     ['Michigan', 0],
     ['Texas Tech', 0],
     ['Florida State', 0],
     ['Florida', 0],
     ['Buffalo', 0],
     ['Marquette', 0],
     ['Syracuse', 0],
     ['Gonzaga', 1],
     ['Michigan', 1],
     ['Texas Tech', 1],
     ['Florida State', 1],
     ['Florida State', 2],
     ['Michigan', 2],
     ['Michigan', 3],
     ["St. John's (NY)", 3],
     ['Purdue', 4],
     ['Virginia Tech', 4],
     ['Virginia Tech', 5]],
      [['Virginia', 0],
     ['Tennessee', 0],
     ['Purdue', 0],
     ['Wisconsin', 0],
     ['Villanova', 0],
     ['Kansas State', 0],
     ['Cincinnati', 0],
     ['Mississippi', 0],
     ['North Carolina', 0],
     ['Kentucky', 0],
     ['Auburn', 0],
     ['Houston', 0],
     ['Northeastern', 0],
     ['Ohio State', 0],
     ['Wofford', 0],
     ['Washington', 0],
     ['Duke', 0],
     ['Michigan State', 0],
     ['Virginia Tech', 0],
     ['Yale', 0],
     ['Louisville', 0],
     ['Maryland', 0],
     ['Mississippi State', 0],
     ['Virginia Commonwealth', 0],
     ['Gonzaga', 0],
     ['Michigan', 0],
     ['Texas Tech', 0],
     ['Florida State', 0],
     ['Nevada', 0],
     ['Buffalo', 0],
     ['Murray State', 0],
     ['Syracuse', 0],
     ['Virginia', 1],
     ['Tennessee', 1],
     ['Villanova', 1],
     ['Wisconsin', 1],
     ['North Carolina', 1],
     ['Wofford', 1],
     ['Auburn', 1],
     ['Houston', 1],
     ['Duke', 1],
     ['Louisville', 1],
     ['Virginia Tech', 1],
     ['Maryland', 1],
     ['Gonzaga', 1],
     ['Michigan', 1],
     ['Buffalo', 1],
     ['Florida State', 1],
     ['Virginia', 2],
     ['Tennessee', 2],
     ['North Carolina', 2],
     ['Wofford', 2],
     ['Duke', 2],
     ['Maryland', 2],
     ['Florida State', 2],
     ['Michigan', 2],
     ['Virginia', 3],
     ['Wofford', 3],
     ['Duke', 3],
     ['Yale', 3],
     ['Michigan', 3],
     ["St. John's (NY)", 3],
     ['Virginia', 4],
     ['Michigan', 4],
     ['Michigan', 5]],
       [['Virginia', 0],
     ['Purdue', 0],
     ['Oregon', 0],
     ['Tennessee', 0],
     ['Oklahoma', 0],
     ['UC-Irvine', 0],
     ['Villanova', 0],
     ['Iowa', 0],
     ['North Carolina', 0],
     ['Kentucky', 0],
     ['Auburn', 0],
     ['Houston', 0],
     ['Washington', 0],
     ['Kansas', 0],
     ['Ohio State', 0],
     ['Wofford', 0],
     ['Duke', 0],
     ['Michigan State', 0],
     ['Virginia Tech', 0],
     ['Louisiana State', 0],
     ['Central Florida', 0],
     ['Liberty', 0],
     ['Maryland', 0],
     ['Minnesota', 0],
     ['Gonzaga', 0],
     ['Texas Tech', 0],
     ['Florida State', 0],
     ['Michigan', 0],
     ['Baylor', 0],
     ['Murray State', 0],
     ['Buffalo', 0],
     ['Florida', 0],
     ['Virginia', 1],
     ['Purdue', 1],
     ['Oregon', 1],
     ['Tennessee', 1],
     ['North Carolina', 1],
     ['Kentucky', 1],
     ['Auburn', 1],
     ['Houston', 1],
     ['Duke', 1],
     ['Michigan State', 1],
     ['Virginia Tech', 1],
     ['Louisiana State', 1],
     ['Gonzaga', 1],
     ['Texas Tech', 1],
     ['Florida State', 1],
     ['Michigan', 1],
     ['Virginia', 2],
     ['Purdue', 2],
     ['North Carolina', 2],
     ['Kentucky', 2],
     ['Virginia Tech', 2],
     ['Michigan State', 2],
     ['Gonzaga', 2],
     ['Texas Tech', 2],
     ['Purdue', 3],
     ['Kentucky', 3],
     ['Michigan State', 3],
     ['Texas Tech', 3],
     ['Kentucky', 4],
     ['Texas Tech', 4],
     ['Texas Tech', 5]]
      ,
     [['Duke',0],
      ['Virginia Commonwealth', 0],
      ['Liberty',0],
      ['Virginia Tech',0],
      ['Maryland',0],
      ['Louisville',0],
      ['Louisiana State',0],
      ['Michigan State',0],
      ['Gonzaga',0],
      ['Baylor',0],
      ['Marquette',0],
      ['Florida State', 0],
      ['Buffalo',0],
      ['Texas Tech',0],
      ['Nevada',0],
      ['Michigan',0],
      ['Virginia',0],
      ['Ole Miss',0],
      ['Oregon',0],
      ['UC-Irvine', 0],
      ['Villanova', 0],
      ['Purdue', 0],
      ['Cincinnati', 0],
      ['Tennessee',0],
      ['North Carolina',0],
      ['Utah State',0],
      ['Auburn',0],
      ['Kansas',0],
      ['Iowa State',0],
      ['Houston',0],
      ['Wofford',0],
      ['Kentucky',0],
      ['Duke',1],
      ['Virginia Tech',1],
      ['Louisiana State',1],
      ['Michigan State',1],
      ['Gonzaga',1],
      ['Florida State', 1],
      ['Texas Tech',1],
      ['Michigan',1],
      ['Virginia',1],
      ['UC-Irvine', 1],
      ['Villanova', 1],
      ['Tennessee',1],
      ['North Carolina',1],
      ['Kansas',1],
      ['Houston',1],
      ['Kentucky',1],
      ['Duke',2],
      ['Louisiana State',2],
      ['Gonzaga',2],
      ['Michigan',2],
      ['Virginia',2],
      ['Tennessee',2],
      ['Auburn',2],
      ['Kentucky',2],
      ['Duke',3],
      ['Gonzaga',3],
      ['Virginia',3],
      ['North Carolina',3],
      ['Duke',4],
      ['Virginia',4],
      ['Duke',5]
      ]
        ]
     return test_list